// <auto-generated>
//     Generated by pipeline/codegen.py from the FastAPI OpenAPI schema.
//     Edit the Pydantic models in pipeline/api.py, not this file.
// </auto-generated>

using System.Collections.Generic;

public static class FinancialsContract {
    public const int LimitMinimum = 1;
    public const int LimitMaximum = 200;
    public const int LimitDefault = 100;
    public const int PerDefault = 10;

    public static readonly string[] Metrics = { "working_capital", "current_ratio", "quick_ratio", "accounts_receivable_turnover", "average_days_to_collect_receivables", "inventory_turnover", "average_days_to_collect_inventory", "debt_to_assets", "debt_to_equity", "number_of_times_interest_is_earned", "net_margin", "asset_turnover_ratio", "return_on_investment", "return_on_equity", "earnings_per_share", "book_value_per_share", "price_earnings_ratio", "dividend_yield" };
    public static readonly string[] DefaultMetrics = { "current_ratio", "quick_ratio", "debt_to_equity", "net_margin", "return_on_equity", "asset_turnover_ratio" };

    public static readonly int[] Years = { 2019, 2020 };

    public static readonly string[] FilterFields = { "assets", "assets_current", "cash_and_equivalents", "inventory", "marketable_securities_current", "receivables_net_current", "accounts_receivable_gross_current", "allowance_for_doubtful_accounts", "property_plant_equipment_net", "liabilities", "liabilities_current", "total_debt", "stockholders_equity", "preferred_stock_value", "revenues", "cost_of_goods_sold", "earnings_before_interest_and_taxes", "net_income", "net_income_available_to_common", "interest_expense", "dividends_paid_common", "preferred_stock_dividends", "common_shares_outstanding", "price_close_annual" };
    public static readonly string[] FilterOperators = { "eq", "ne", "lt", "lte", "gt", "gte" };
    public const string FilterUnits = "Figures are in millions except price_close_annual, which is dollars per share. Revenue over one billion dollars is revenues:gt:1000.";

    public static readonly Dictionary<string, string[]> MetricCategories =
        new Dictionary<string, string[]> {
            { "liquidity", new[] { "working_capital", "current_ratio", "quick_ratio" } },
            { "efficiency", new[] { "accounts_receivable_turnover", "average_days_to_collect_receivables", "inventory_turnover", "average_days_to_collect_inventory", "asset_turnover_ratio" } },
            { "solvency", new[] { "debt_to_assets", "debt_to_equity", "number_of_times_interest_is_earned" } },
            { "profitability", new[] { "net_margin", "return_on_investment", "return_on_equity", "earnings_per_share" } },
            { "valuation", new[] { "book_value_per_share", "price_earnings_ratio", "dividend_yield" } },
        };
}
