"""Emit the C# side of the /sheet contract from the FastAPI OpenAPI schema.

The Unity tool used to repeat the API's constraints by hand: Limits(1, 200)
against Query(ge=1, le=200), and a free-text metric name against RATIOS. Both
now come from one source, and test_codegen.py fails if the checked-in file
drifts from what this produces.

    python codegen.py            rewrite the generated file
    python codegen.py --check    exit non-zero if it is stale
"""

import argparse
import sys
from pathlib import Path

TARGET = Path(__file__).resolve().parents[1] / "Assets/Source/Gemini/Tools/FinancialsContract.g.cs"

HEADER = """// <auto-generated>
//     Generated by pipeline/codegen.py from the FastAPI OpenAPI schema.
//     Edit the Pydantic models in pipeline/api.py, not this file.
// </auto-generated>

using System.Collections.Generic;

public static class FinancialsContract {
"""


def schema():
    import api

    return api.app.openapi()


def parameters(document, path, method="get"):
    return {p["name"]: p["schema"] for p in document["paths"][path][method]["parameters"]}


def csharp_array(name, values):
    body = ", ".join(f'"{v}"' for v in values)
    return f"    public static readonly string[] {name} = {{ {body} }};\n"


def csharp_string(name, value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'    public const string {name} = "{escaped}";\n'


def csharp_dictionary(name, mapping):
    lines = [f"    public static readonly Dictionary<string, string[]> {name} ="]
    lines.append("        new Dictionary<string, string[]> {")
    for key, values in mapping.items():
        body = ", ".join(f'"{v}"' for v in values)
        lines.append(f'            {{ "{key}", new[] {{ {body} }} }},')
    lines.append("        };")
    return "\n".join(lines) + "\n"


def render(document):
    from metrics import CATEGORIES, UNIT_NOTE

    sheet = parameters(document, "/sheet")
    limit = sheet["limit"]
    schemas = document["components"]["schemas"]

    out = [HEADER]
    out.append(f'    public const int LimitMinimum = {limit["minimum"]};\n')
    out.append(f'    public const int LimitMaximum = {limit["maximum"]};\n')
    out.append(f'    public const int LimitDefault = {limit["default"]};\n')
    out.append(f'    public const int PerDefault = {sheet["per"]["default"]};\n\n')
    out.append(csharp_array("Metrics", schemas["MetricName"]["enum"]))
    out.append(csharp_array("DefaultMetrics", sheet["metrics"]["default"]))
    out.append(f'\n    public static readonly int[] Years = {{ {", ".join(str(y) for y in sheet["years"]["default"])} }};\n')

    # The filter surface. Separate from Metrics on purpose: the app validates a
    # filter against this before spending a round trip, exactly as it already
    # does a metric name, and the two lists cannot be confused for each other.
    out.append("\n")
    out.append(csharp_array("FilterFields", schemas["FieldName"]["enum"]))
    out.append(csharp_array("FilterOperators", schemas["Operator"]["enum"]))

    # A filter written in the wrong unit returns an empty sheet rather than an
    # error, so the tool description carries the unit into the model's context.
    out.append(csharp_string("FilterUnits", UNIT_NOTE))

    # Not from the schema: OpenAPI types 'categories' as an open dictionary, so
    # the category names are not in the document. They come from metrics.py,
    # which is where the API reads them from too.
    out.append("\n")
    out.append(csharp_dictionary("MetricCategories", CATEGORIES))

    out.append("}\n")
    return "".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = render(schema())
    if args.check:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != generated:
            print(f"{TARGET} is stale; run: python codegen.py", file=sys.stderr)
            return 1
        print(f"{TARGET} is up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(generated)
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
